"""
Project Euler - Problem 2: Even Fibonacci Numbers

Description:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3,5,8,....
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
Author:
Max Fils Remfort
"""

a = [1,2]
max_sum = 4000000
is_not_bigger = True
current_index =1
prev_index = 0

while is_not_bigger:
    sum = a[current_index]+a[prev_index]
    if(sum<max_sum):
        a.append(sum)
        current_index += 1
        prev_index += 1
    else:
        is_not_bigger = False

even_sum = 0
for i in range(len(a)):
    if a[i] % 2 == 0:
        even_sum += a[i]

print(even_sum)